@echo off
REM Placeholder until the setup icon is run for the first time.
set BROKER_HOST=
set BROKER_PORT=1883
set TOPIC=
set SECRET=SHUTDOWN_NOW_9x7q
set RESTART_SECRET=RESTART_NOW_9x7q
set REFRESH_SECRET=REFRESH_NOW_9x7q
set CLEARCACHE_SECRET=CLEARCACHE_NOW_9x7q
set STOPKM_SECRET=STOPKM_NOW_9x7q
set RESTARTKM_SECRET=RESTARTKM_NOW_9x7q
set BROWSER_PROCESS=MythricClient
set POWERTOYS_PATH=%LocalAppData%\PowerToys\PowerToys.exe
