Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$form = New-Object System.Windows.Forms.Form
$form.Text = "M3 Shutdown Listener Setup"
$form.Size = New-Object System.Drawing.Size(380,460)
$form.StartPosition = "CenterScreen"
$form.FormBorderStyle = "FixedDialog"
$form.MaximizeBox = $false

$labelIP = New-Object System.Windows.Forms.Label
$labelIP.Text = "M3 Broker IP Address:"
$labelIP.Location = New-Object System.Drawing.Point(20,20)
$labelIP.AutoSize = $true
$form.Controls.Add($labelIP)

$textIP = New-Object System.Windows.Forms.TextBox
$textIP.Location = New-Object System.Drawing.Point(20,45)
$textIP.Size = New-Object System.Drawing.Size(320,20)
$form.Controls.Add($textIP)

$labelXFrame = New-Object System.Windows.Forms.Label
$labelXFrame.Text = "Which X-Frame within the venue is this?"
$labelXFrame.Location = New-Object System.Drawing.Point(20,85)
$labelXFrame.AutoSize = $true
$form.Controls.Add($labelXFrame)

$radioX1 = New-Object System.Windows.Forms.RadioButton
$radioX1.Text = "This is my only or first X-Frame"
$radioX1.Location = New-Object System.Drawing.Point(20,110)
$radioX1.Size = New-Object System.Drawing.Size(320,20)
$radioX1.Checked = $true
$form.Controls.Add($radioX1)

$radioX2 = New-Object System.Windows.Forms.RadioButton
$radioX2.Text = "This is X-Frame number 2"
$radioX2.Location = New-Object System.Drawing.Point(20,135)
$radioX2.Size = New-Object System.Drawing.Size(320,20)
$form.Controls.Add($radioX2)

$labelPC = New-Object System.Windows.Forms.Label
$labelPC.Text = "Which PC is this?"
$labelPC.Location = New-Object System.Drawing.Point(20,175)
$labelPC.AutoSize = $true
$form.Controls.Add($labelPC)

$comboPC = New-Object System.Windows.Forms.ComboBox
$comboPC.Location = New-Object System.Drawing.Point(20,200)
$comboPC.Size = New-Object System.Drawing.Size(150,20)
$comboPC.DropDownStyle = "DropDownList"
1..6 | ForEach-Object { $comboPC.Items.Add("PC$_") } | Out-Null
$comboPC.SelectedIndex = 0
$form.Controls.Add($comboPC)

$labelBrowser = New-Object System.Windows.Forms.Label
$labelBrowser.Text = "Browser process name (e.g. MythricClient):"
$labelBrowser.Location = New-Object System.Drawing.Point(20,240)
$labelBrowser.AutoSize = $true
$form.Controls.Add($labelBrowser)

$textBrowser = New-Object System.Windows.Forms.TextBox
$textBrowser.Location = New-Object System.Drawing.Point(20,265)
$textBrowser.Size = New-Object System.Drawing.Size(320,20)
$textBrowser.Text = "MythricClient"
$form.Controls.Add($textBrowser)

$labelPowerToys = New-Object System.Windows.Forms.Label
$labelPowerToys.Text = "PowerToys.exe path:"
$labelPowerToys.Location = New-Object System.Drawing.Point(20,300)
$labelPowerToys.AutoSize = $true
$form.Controls.Add($labelPowerToys)

$textPowerToys = New-Object System.Windows.Forms.TextBox
$textPowerToys.Location = New-Object System.Drawing.Point(20,325)
$textPowerToys.Size = New-Object System.Drawing.Size(320,20)
$textPowerToys.Text = "C:\Program Files\PowerToys\PowerToys.exe"
$form.Controls.Add($textPowerToys)

$buttonSave = New-Object System.Windows.Forms.Button
$buttonSave.Text = "Save"
$buttonSave.Location = New-Object System.Drawing.Point(20,375)
$buttonSave.Size = New-Object System.Drawing.Size(100,30)
$form.Controls.Add($buttonSave)

$buttonSave.Add_Click({
    $ip = $textIP.Text.Trim()
    if ($ip -eq "") {
        [System.Windows.Forms.MessageBox]::Show("Please enter the M3 broker IP address.", "Missing IP", "OK", "Warning")
        return
    }
    $xframePrefix = if ($radioX2.Checked) { "X2" } else { "X1" }
    $pcNumber = $comboPC.SelectedItem.ToString()
    $topic = "$xframePrefix$pcNumber"
    $browser = $textBrowser.Text.Trim()
    if ($browser -eq "") { $browser = "MythricClient" }
    $ptPath = $textPowerToys.Text.Trim()
    if ($ptPath -eq "") { $ptPath = "C:\Program Files\PowerToys\PowerToys.exe" }
    $configPath = Join-Path $PSScriptRoot "config.bat"

    $lines = @(
        "@echo off",
        "REM Auto-generated by setup.ps1 - re-run setup to change these instead of editing by hand",
        "set BROKER_HOST=$ip",
        "set BROKER_PORT=1883",
        "set TOPIC=$topic",
        "set SECRET=SHUTDOWN_NOW_9x7q",
        "set RESTART_SECRET=RESTART_NOW_9x7q",
        "set REFRESH_SECRET=REFRESH_NOW_9x7q",
        "set CLEARCACHE_SECRET=CLEARCACHE_NOW_9x7q",
        "set STOPKM_SECRET=STOPKM_NOW_9x7q",
        "set RESTARTKM_SECRET=RESTARTKM_NOW_9x7q",
        "set BROWSER_PROCESS=$browser",
        "set POWERTOYS_PATH=$ptPath"
    )
    $lines | Set-Content -Path $configPath -Encoding ASCII

    # Only PC6 ever needs PowerToys auto-installed (the Crime Scene desk PC).
    # Since PC6 could get picked for other reasons too (wrong X-Frame, a future
    # unrelated PC6), always confirm before actually installing anything.
    if ($pcNumber -eq "PC6") {
        $ptConfirm = [System.Windows.Forms.MessageBox]::Show("Are you installing Crime Scene now?", "PowerToys Setup", "YesNo", "Question")
        if ($ptConfirm -eq "Yes") {
            $installScript = Join-Path $PSScriptRoot "install_powertoys.ps1"
            Start-Process -FilePath "powershell.exe" -ArgumentList @("-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "`"$installScript`"") -Wait
        }
    }

    [System.Windows.Forms.MessageBox]::Show("Saved! This PC is set up as $topic, connecting to $ip.", "Setup Complete", "OK", "Information")
    $form.Close()
})

[void]$form.ShowDialog()
